class OldThrowableTest
!!!2748827.java!!!	test_ConstructorLStringLThrowable() : void
        String message = "Test message";
        NullPointerException npe = new NullPointerException();
        Throwable thr = new Throwable(message, npe);
        assertEquals("message is incorrect.", message, thr.getMessage());
        assertEquals("cause is incorrect.", npe, thr.getCause());

        thr = new Throwable(null, npe);
        assertNull("message is not null.", thr.getMessage());
        assertEquals("cause is incorrect.", npe, thr.getCause());

        thr = new Throwable(message, null);
        assertEquals("message is incorrect.", message, thr.getMessage());
        assertNull("cause is not null.", thr.getCause());
!!!2748955.java!!!	test_ConstructorLThrowable() : void

        NullPointerException npe = new NullPointerException();
        Throwable thr = new Throwable(npe);

        assertEquals("Returned cause is incorrect.", npe, thr.getCause());

        thr = new Throwable((Throwable) null);
        assertNull("The cause is not null.", thr.getCause());
!!!2749083.java!!!	test_getLocalizedMessage() : void
        String testMessage = "Test message";
        Throwable e = new Throwable(testMessage);
        assertEquals("Returned incorrect localized message.",
                testMessage, e.getLocalizedMessage());

        TestThrowable tt = new TestThrowable(testMessage);
        assertEquals("localized message", tt.getLocalizedMessage());
!!!2749467.java!!!	test_getStackTrace() : void
        String message = "Test message";
        NullPointerException npe = new NullPointerException();
        Throwable thr = new Throwable(message, npe);
        StackTraceElement[] ste = thr.getStackTrace();
        assertNotNull("Returned stack trace is empty", ste.length != 0);
!!!2749595.java!!!	test_initCause() : void
        String message = "Test message";
        NullPointerException npe = new NullPointerException();
        IllegalArgumentException iae = new IllegalArgumentException();
        Throwable thr = new Throwable();
        thr.initCause(iae);
        assertEquals("getCause returns incorrect cause.", iae, thr.getCause());

        thr = new Throwable("message");
        thr.initCause(npe);
        assertEquals("getCause returns incorrect cause.", npe, thr.getCause());

        thr = new Throwable(message, npe);
        try {
            thr.initCause(iae);
            fail("IllegalStateException was not thrown.");
        } catch(IllegalStateException ise) {
            //expected
        }

        thr = new Throwable(npe);
        try {
            thr.initCause(iae);
            fail("IllegalStateException was not thrown.");
        } catch(IllegalStateException ise) {
            //expected
        }

        thr = new Throwable();
        try {
            thr.initCause(thr);
            fail("IllegalArgumentException was not thrown.");
        } catch(IllegalArgumentException ise) {
            //expected
        }
!!!2749723.java!!!	test_setStackTrace() : void
        NullPointerException npe = new NullPointerException();
        Throwable thr = new Throwable(npe);
        StackTraceElement[] ste = thr.getStackTrace();
        Throwable thr1 = new Throwable(npe);
        thr1.setStackTrace(ste);
        assertEquals(ste.length, thr1.getStackTrace().length);

        try {
            thr.setStackTrace(null);
            fail("NullPointerException is not thrown.");
        } catch(NullPointerException np) {
            //expected
        }
